<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CauHoiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cau_hoi')->insert([
            [
                'maCH' => 1,
                'noiDung' => 'Cơ sở dữ liệu là gì?',
                'dapAnA' => 'Tập hợp dữ liệu liên quan',
                'dapAnB' => 'Ngôn ngữ lập trình',
                'dapAnC' => 'Hệ điều hành',
                'dapAnD' => 'Trình duyệt',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 2,
                'noiDung' => 'Hệ quản trị cơ sở dữ liệu (DBMS) là gì?',
                'dapAnA' => 'Hệ điều hành',
                'dapAnB' => 'Phần mềm quản lý CSDL',
                'dapAnC' => 'Trình duyệt',
                'dapAnD' => 'Biên dịch',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 3,
                'noiDung' => 'Đặc điểm chính của cơ sở dữ liệu?',
                'dapAnA' => 'Truy cập đồng thời',
                'dapAnB' => 'Không lưu trữ dữ liệu',
                'dapAnC' => 'Chỉ đọc dữ liệu',
                'dapAnD' => 'Không có ràng buộc',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 4,
                'noiDung' => 'Ví dụ của hệ quản trị CSDL?',
                'dapAnA' => 'MS Word',
                'dapAnB' => 'MySQL',
                'dapAnC' => 'Photoshop',
                'dapAnD' => 'Chrome',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 5,
                'noiDung' => 'CSDL giúp gì?',
                'dapAnA' => 'Lưu trữ và quản lý dữ liệu',
                'dapAnB' => 'Soạn thảo văn bản',
                'dapAnC' => 'Vẽ đồ họa',
                'dapAnD' => 'Lướt web',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 6,
                'noiDung' => 'Tính toàn vẹn dữ liệu là?',
                'dapAnA' => 'Giữ dữ liệu đúng đắn',
                'dapAnB' => 'Xóa dữ liệu',
                'dapAnC' => 'Chia sẻ file',
                'dapAnD' => 'In tài liệu',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 7,
                'noiDung' => 'CSDL phân tán là?',
                'dapAnA' => 'Dữ liệu nằm nhiều nơi',
                'dapAnB' => 'Dữ liệu 1 file',
                'dapAnC' => 'Dữ liệu không truy cập',
                'dapAnD' => 'Dữ liệu không chia sẻ',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 8,
                'noiDung' => 'Tập tin dữ liệu là gì?',
                'dapAnA' => 'Dữ liệu lưu rải rác',
                'dapAnB' => 'Dữ liệu lưu có cấu trúc',
                'dapAnC' => 'Không lưu dữ liệu',
                'dapAnD' => 'Không truy xuất được',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 9,
                'noiDung' => 'Ứng dụng nào sử dụng CSDL?',
                'dapAnA' => 'Hệ thống quản lý thư viện',
                'dapAnB' => 'Paint',
                'dapAnC' => 'Notepad',
                'dapAnD' => 'Trình duyệt',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 10,
                'noiDung' => 'CSDL thường lưu dữ liệu dạng?',
                'dapAnA' => 'File văn bản',
                'dapAnB' => 'File ảnh',
                'dapAnC' => 'Bảng dữ liệu',
                'dapAnD' => 'Video',
                'dapAnDung' => 'C',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:49:28',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 1,
                'created_at' => '2025-07-06 17:49:28',
                'updated_at' => '2025-07-06 17:49:28',
            ],
            [
                'maCH' => 11,
                'noiDung' => 'Mô hình dữ liệu nào phổ biến nhất?',
                'dapAnA' => 'Phân cấp',
                'dapAnB' => 'Mạng',
                'dapAnC' => 'Quan hệ',
                'dapAnD' => 'Đối tượng',
                'dapAnDung' => 'C',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 12,
                'noiDung' => 'Mô hình quan hệ lưu dữ liệu dạng?',
                'dapAnA' => 'Bảng',
                'dapAnB' => 'Cây',
                'dapAnC' => 'Danh sách',
                'dapAnD' => 'Đồ thị',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 13,
                'noiDung' => 'Mô hình dữ liệu có thành phần gì?',
                'dapAnA' => 'Cấu trúc, ràng buộc, thao tác',
                'dapAnB' => 'Cấu trúc',
                'dapAnC' => 'Thao tác',
                'dapAnD' => 'Ràng buộc',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 14,
                'noiDung' => 'Mô hình phân cấp dữ liệu tổ chức dạng?',
                'dapAnA' => 'Cây',
                'dapAnB' => 'Bảng',
                'dapAnC' => 'Đồ thị',
                'dapAnD' => 'Danh sách',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 15,
                'noiDung' => 'Mô hình mạng có đặc điểm gì?',
                'dapAnA' => 'Nhiều quan hệ phức tạp',
                'dapAnB' => 'Chỉ 1 quan hệ',
                'dapAnC' => 'Không quan hệ',
                'dapAnD' => 'Quan hệ 1-1',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 16,
                'noiDung' => 'Quan hệ 1-n là?',
                'dapAnA' => 'Một bản ghi liên kết nhiều bản ghi',
                'dapAnB' => 'Một bản ghi chỉ 1 liên kết',
                'dapAnC' => 'Không liên kết',
                'dapAnD' => 'Liên kết toàn bộ',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 17,
                'noiDung' => 'Quan hệ n-n là?',
                'dapAnA' => 'Nhiều liên kết nhiều',
                'dapAnB' => 'Không liên kết',
                'dapAnC' => 'Chỉ 1 liên kết',
                'dapAnD' => 'Liên kết 1 chiều',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 18,
                'noiDung' => 'Dữ liệu trong mô hình quan hệ gọi là?',
                'dapAnA' => 'Thuộc tính',
                'dapAnB' => 'Bản ghi',
                'dapAnC' => 'Trường',
                'dapAnD' => 'Cột',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 19,
                'noiDung' => 'Mô hình dữ liệu quyết định?',
                'dapAnA' => 'Cách lưu và xử lý dữ liệu',
                'dapAnB' => 'Màu giao diện',
                'dapAnC' => 'Hệ điều hành',
                'dapAnD' => 'Trình duyệt',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 20,
                'noiDung' => 'Khóa chính là?',
                'dapAnA' => 'Xác định duy nhất bản ghi',
                'dapAnB' => 'Dữ liệu trùng nhau',
                'dapAnC' => 'Dữ liệu rỗng',
                'dapAnD' => 'Dữ liệu tạm',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:16',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 2,
                'created_at' => '2025-07-06 17:50:16',
                'updated_at' => '2025-07-06 17:50:16',
            ],
            [
                'maCH' => 21,
                'noiDung' => 'SQL là gì?',
                'dapAnA' => 'Ngôn ngữ truy vấn',
                'dapAnB' => 'Ngôn ngữ lập trình',
                'dapAnC' => 'Phần mềm',
                'dapAnD' => 'Hệ điều hành',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 22,
                'noiDung' => 'Lệnh SELECT dùng để?',
                'dapAnA' => 'Chèn dữ liệu',
                'dapAnB' => 'Truy vấn dữ liệu',
                'dapAnC' => 'Xóa dữ liệu',
                'dapAnD' => 'Cập nhật dữ liệu',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 23,
                'noiDung' => 'Lệnh INSERT dùng để?',
                'dapAnA' => 'Chèn dữ liệu',
                'dapAnB' => 'Xóa dữ liệu',
                'dapAnC' => 'Truy vấn dữ liệu',
                'dapAnD' => 'Cập nhật dữ liệu',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 24,
                'noiDung' => 'Lệnh DELETE dùng để?',
                'dapAnA' => 'Chèn dữ liệu',
                'dapAnB' => 'Xóa dữ liệu',
                'dapAnC' => 'Truy vấn dữ liệu',
                'dapAnD' => 'Cập nhật dữ liệu',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 25,
                'noiDung' => 'Lệnh UPDATE dùng để?',
                'dapAnA' => 'Cập nhật dữ liệu',
                'dapAnB' => 'Xóa dữ liệu',
                'dapAnC' => 'Chèn dữ liệu',
                'dapAnD' => 'Truy vấn dữ liệu',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 26,
                'noiDung' => 'DDL là gì?',
                'dapAnA' => 'Ngôn ngữ định nghĩa dữ liệu',
                'dapAnB' => 'Ngôn ngữ thao tác dữ liệu',
                'dapAnC' => 'Ngôn ngữ lập trình',
                'dapAnD' => 'Ngôn ngữ báo cáo',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 27,
                'noiDung' => 'DML là gì?',
                'dapAnA' => 'Ngôn ngữ thao tác dữ liệu',
                'dapAnB' => 'Ngôn ngữ định nghĩa dữ liệu',
                'dapAnC' => 'Ngôn ngữ lập trình',
                'dapAnD' => 'Ngôn ngữ báo cáo',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 28,
                'noiDung' => 'Câu lệnh tạo bảng?',
                'dapAnA' => 'CREATE TABLE',
                'dapAnB' => 'INSERT INTO',
                'dapAnC' => 'SELECT *',
                'dapAnD' => 'DELETE',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 29,
                'noiDung' => 'Câu lệnh xóa bảng?',
                'dapAnA' => 'DROP TABLE',
                'dapAnB' => 'DELETE',
                'dapAnC' => 'UPDATE',
                'dapAnD' => 'INSERT',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 30,
                'noiDung' => 'Câu lệnh thêm cột?',
                'dapAnA' => 'ALTER TABLE',
                'dapAnB' => 'SELECT',
                'dapAnC' => 'DROP',
                'dapAnD' => 'UPDATE',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:50:47',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 3,
                'created_at' => '2025-07-06 17:50:47',
                'updated_at' => '2025-07-06 17:50:47',
            ],
            [
                'maCH' => 31,
                'noiDung' => 'Thiết kế cơ sở dữ liệu gồm mấy bước chính?',
                'dapAnA' => '3',
                'dapAnB' => '4',
                'dapAnC' => '5',
                'dapAnD' => '6',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 32,
                'noiDung' => 'Thiết kế lôgic nghĩa là?',
                'dapAnA' => 'Thiết kế bảng và quan hệ',
                'dapAnB' => 'Thiết kế giao diện',
                'dapAnC' => 'Thiết kế mạng',
                'dapAnD' => 'Thiết kế phần cứng',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 33,
                'noiDung' => 'Mục tiêu của thiết kế cơ sở dữ liệu?',
                'dapAnA' => 'Hiệu quả và toàn vẹn dữ liệu',
                'dapAnB' => 'Giao diện đẹp',
                'dapAnC' => 'Dữ liệu nhỏ gọn',
                'dapAnD' => 'Nhanh tải web',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 34,
                'noiDung' => 'Thiết kế vật lý là?',
                'dapAnA' => 'Thiết kế lưu trữ thực tế',
                'dapAnB' => 'Thiết kế màn hình',
                'dapAnC' => 'Thiết kế biểu mẫu',
                'dapAnD' => 'Thiết kế sơ đồ',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 35,
                'noiDung' => 'Chuẩn hóa dữ liệu nhằm?',
                'dapAnA' => 'Tránh dư thừa',
                'dapAnB' => 'Tăng tốc độ nhập',
                'dapAnC' => 'Tăng dung lượng',
                'dapAnD' => 'Tạo báo cáo nhanh',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 36,
                'noiDung' => 'Quan hệ 1-1 thể hiện?',
                'dapAnA' => 'Mỗi bản ghi A gắn 1 bản ghi B',
                'dapAnB' => 'Nhiều A gắn nhiều B',
                'dapAnC' => 'Không gắn kết',
                'dapAnD' => 'Tất cả sai',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 37,
                'noiDung' => 'Quan hệ 1-n thể hiện?',
                'dapAnA' => 'Một A nhiều B',
                'dapAnB' => 'Một A một B',
                'dapAnC' => 'Một A không B',
                'dapAnD' => 'Nhiều A nhiều B',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 38,
                'noiDung' => 'Quan hệ n-n thể hiện?',
                'dapAnA' => 'Nhiều A nhiều B',
                'dapAnB' => 'Một A một B',
                'dapAnC' => 'Không liên kết',
                'dapAnD' => 'Một A nhiều B',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 39,
                'noiDung' => 'Chuẩn 1NF yêu cầu?',
                'dapAnA' => 'Không lặp nhóm',
                'dapAnB' => 'Không khóa chính',
                'dapAnC' => 'Không quan hệ',
                'dapAnD' => 'Không thuộc tính',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 40,
                'noiDung' => 'Chuẩn 2NF yêu cầu?',
                'dapAnA' => 'Thuộc tính không phụ thuộc 1 phần',
                'dapAnB' => 'Không có quan hệ',
                'dapAnC' => 'Không có bảng',
                'dapAnD' => 'Không có thuộc tính',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:52:04',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 4,
                'created_at' => '2025-07-06 17:52:04',
                'updated_at' => '2025-07-06 17:52:04',
            ],
            [
                'maCH' => 41,
                'noiDung' => 'Quản trị cơ sở dữ liệu gồm?',
                'dapAnA' => 'Sao lưu, bảo mật, tối ưu',
                'dapAnB' => 'Vẽ sơ đồ',
                'dapAnC' => 'Tạo website',
                'dapAnD' => 'Tạo file văn bản',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 42,
                'noiDung' => 'Sao lưu dữ liệu để?',
                'dapAnA' => 'Phục hồi khi lỗi',
                'dapAnB' => 'Tăng tốc',
                'dapAnC' => 'Giảm dung lượng',
                'dapAnD' => 'Chia sẻ nhanh',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 43,
                'noiDung' => 'Bảo mật dữ liệu để?',
                'dapAnA' => 'Ngăn truy cập trái phép',
                'dapAnB' => 'Tăng tốc',
                'dapAnC' => 'Giảm dung lượng',
                'dapAnD' => 'Tạo báo cáo',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 44,
                'noiDung' => 'Tối ưu truy vấn để?',
                'dapAnA' => 'Tăng hiệu năng',
                'dapAnB' => 'Giảm bảo mật',
                'dapAnC' => 'Tăng dung lượng',
                'dapAnD' => 'Tạo báo cáo',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 45,
                'noiDung' => 'Người quản trị CSDL là?',
                'dapAnA' => 'DBA',
                'dapAnB' => 'CEO',
                'dapAnC' => 'CIO',
                'dapAnD' => 'CTO',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 46,
                'noiDung' => 'Phân quyền trong CSDL để?',
                'dapAnA' => 'Giới hạn quyền truy cập',
                'dapAnB' => 'Tăng tốc',
                'dapAnC' => 'Giảm dung lượng',
                'dapAnD' => 'Tạo báo cáo',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 47,
                'noiDung' => 'Kiểm tra tính toàn vẹn để?',
                'dapAnA' => 'Dữ liệu chính xác',
                'dapAnB' => 'Giảm dung lượng',
                'dapAnC' => 'Tạo file',
                'dapAnD' => 'Vẽ sơ đồ',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 48,
                'noiDung' => 'Bảo mật vật lý là?',
                'dapAnA' => 'Bảo vệ phần cứng',
                'dapAnB' => 'Bảo vệ phần mềm',
                'dapAnC' => 'Bảo vệ dữ liệu',
                'dapAnD' => 'Bảo vệ tài liệu',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 49,
                'noiDung' => 'Bảo mật logic là?',
                'dapAnA' => 'Bảo vệ truy cập dữ liệu',
                'dapAnB' => 'Bảo vệ thiết bị',
                'dapAnC' => 'Bảo vệ file word',
                'dapAnD' => 'Bảo vệ hình ảnh',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 50,
                'noiDung' => 'Sao lưu định kỳ để?',
                'dapAnA' => 'Luôn có bản dự phòng mới',
                'dapAnB' => 'Giảm tốc độ',
                'dapAnC' => 'Tăng dung lượng',
                'dapAnD' => 'Xóa dữ liệu',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:20',
                'maNguoiTao' => 2,
                'maMonHoc' => 1,
                'maChuong' => 5,
                'created_at' => '2025-07-06 17:52:20',
                'updated_at' => '2025-07-06 17:52:20',
            ],
            [
                'maCH' => 51,
                'noiDung' => 'Lập trình hướng đối tượng là gì?',
                'dapAnA' => 'Lập trình dựa trên đối tượng',
                'dapAnB' => 'Lập trình dựa trên hàm',
                'dapAnC' => 'Lập trình dựa trên cấu trúc',
                'dapAnD' => 'Lập trình không cấu trúc',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 52,
                'noiDung' => 'Đặc trưng của OOP?',
                'dapAnA' => 'Đóng gói, kế thừa, đa hình',
                'dapAnB' => 'Hàm, thủ tục',
                'dapAnC' => 'Biến toàn cục',
                'dapAnD' => 'Gán trực tiếp',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 53,
                'noiDung' => 'Đối tượng là?',
                'dapAnA' => 'Thực thể có trạng thái và hành vi',
                'dapAnB' => 'Biến',
                'dapAnC' => 'Hàm',
                'dapAnD' => 'Cấu trúc',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 54,
                'noiDung' => 'Lớp là?',
                'dapAnA' => 'Khuôn mẫu tạo đối tượng',
                'dapAnB' => 'Biến toàn cục',
                'dapAnC' => 'Hàm chính',
                'dapAnD' => 'Hàm con',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 55,
                'noiDung' => 'OOP giúp?',
                'dapAnA' => 'Tái sử dụng mã',
                'dapAnB' => 'Tăng lỗi',
                'dapAnC' => 'Khó bảo trì',
                'dapAnD' => 'Giảm tính mở rộng',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 56,
                'noiDung' => 'Đóng gói nghĩa là?',
                'dapAnA' => 'Giấu dữ liệu',
                'dapAnB' => 'Lộ dữ liệu',
                'dapAnC' => 'Không cần bảo vệ',
                'dapAnD' => 'Xóa dữ liệu',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 57,
                'noiDung' => 'Kế thừa nghĩa là?',
                'dapAnA' => 'Lớp con thừa hưởng lớp cha',
                'dapAnB' => 'Không có liên kết',
                'dapAnC' => 'Không thể dùng lại',
                'dapAnD' => 'Tạo mới hoàn toàn',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 58,
                'noiDung' => 'Đa hình nghĩa là?',
                'dapAnA' => 'Một hàm nhiều cách thực hiện',
                'dapAnB' => 'Một hàm chỉ 1 cách',
                'dapAnC' => 'Không thể mở rộng',
                'dapAnD' => 'Giống nhau hoàn toàn',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 59,
                'noiDung' => 'Tính trừu tượng nghĩa là?',
                'dapAnA' => 'Ẩn chi tiết',
                'dapAnB' => 'Hiện tất cả',
                'dapAnC' => 'Không bảo vệ',
                'dapAnD' => 'Tăng lỗi',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 60,
                'noiDung' => 'OOP ra đời để?',
                'dapAnA' => 'Giải quyết phức tạp',
                'dapAnB' => 'Tăng lỗi',
                'dapAnC' => 'Giảm bảo trì',
                'dapAnD' => 'Khó đọc mã',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:52:50',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 6,
                'created_at' => '2025-07-06 17:52:50',
                'updated_at' => '2025-07-06 17:52:50',
            ],
            [
                'maCH' => 61,
                'noiDung' => 'Lớp mô tả?',
                'dapAnA' => 'Thuộc tính và phương thức',
                'dapAnB' => 'Chỉ thuộc tính',
                'dapAnC' => 'Chỉ phương thức',
                'dapAnD' => 'Không mô tả',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 62,
                'noiDung' => 'Đối tượng là?',
                'dapAnA' => 'Thể hiện của lớp',
                'dapAnB' => 'Một hàm',
                'dapAnC' => 'Một biến',
                'dapAnD' => 'Một thư viện',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 63,
                'noiDung' => 'Thuộc tính là?',
                'dapAnA' => 'Đặc điểm đối tượng',
                'dapAnB' => 'Hành vi đối tượng',
                'dapAnC' => 'Hàm toàn cục',
                'dapAnD' => 'Hàm main',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 64,
                'noiDung' => 'Phương thức là?',
                'dapAnA' => 'Hành vi đối tượng',
                'dapAnB' => 'Thuộc tính',
                'dapAnC' => 'Biến toàn cục',
                'dapAnD' => 'Biến cục bộ',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 65,
                'noiDung' => 'Constructor dùng để?',
                'dapAnA' => 'Khởi tạo đối tượng',
                'dapAnB' => 'Xóa đối tượng',
                'dapAnC' => 'Gọi main',
                'dapAnD' => 'Xóa class',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 66,
                'noiDung' => 'Destructor dùng để?',
                'dapAnA' => 'Giải phóng đối tượng',
                'dapAnB' => 'Tạo đối tượng',
                'dapAnC' => 'Gọi main',
                'dapAnD' => 'Tạo class',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 67,
                'noiDung' => 'Từ khóa new dùng để?',
                'dapAnA' => 'Cấp phát bộ nhớ',
                'dapAnB' => 'Giải phóng bộ nhớ',
                'dapAnC' => 'Xóa đối tượng',
                'dapAnD' => 'Xóa class',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 68,
                'noiDung' => 'Từ khóa delete dùng để?',
                'dapAnA' => 'Giải phóng bộ nhớ',
                'dapAnB' => 'Tạo đối tượng',
                'dapAnC' => 'Tạo class',
                'dapAnD' => 'Khởi tạo',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 69,
                'noiDung' => 'Đối tượng có thể?',
                'dapAnA' => 'Gọi phương thức',
                'dapAnB' => 'Không gọi gì',
                'dapAnC' => 'Chỉ lưu dữ liệu',
                'dapAnD' => 'Chỉ lưu tên',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 70,
                'noiDung' => 'Một lớp có thể có?',
                'dapAnA' => 'Nhiều đối tượng',
                'dapAnB' => 'Chỉ 1 đối tượng',
                'dapAnC' => 'Không có đối tượng',
                'dapAnD' => '1 đối tượng duy nhất',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:53:05',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 7,
                'created_at' => '2025-07-06 17:53:05',
                'updated_at' => '2025-07-06 17:53:05',
            ],
            [
                'maCH' => 71,
                'noiDung' => 'Kế thừa là?',
                'dapAnA' => 'Lớp con thừa hưởng lớp cha',
                'dapAnB' => 'Không liên kết',
                'dapAnC' => 'Không thể dùng lại',
                'dapAnD' => 'Tạo mới hoàn toàn',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 72,
                'noiDung' => 'Từ khóa kế thừa trong C++?',
                'dapAnA' => 'public',
                'dapAnB' => 'extends',
                'dapAnC' => 'inherit',
                'dapAnD' => 'implements',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 73,
                'noiDung' => 'Kế thừa giúp?',
                'dapAnA' => 'Tái sử dụng mã',
                'dapAnB' => 'Tăng lỗi',
                'dapAnC' => 'Khó mở rộng',
                'dapAnD' => 'Không tái sử dụng',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 74,
                'noiDung' => 'Kế thừa đơn nghĩa là?',
                'dapAnA' => 'Lớp con từ 1 lớp cha',
                'dapAnB' => 'Lớp con từ nhiều lớp',
                'dapAnC' => 'Không kế thừa',
                'dapAnD' => 'Kế thừa toàn bộ',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 75,
                'noiDung' => 'Kế thừa đa nghĩa là?',
                'dapAnA' => 'Lớp con từ nhiều lớp cha',
                'dapAnB' => 'Không kế thừa',
                'dapAnC' => 'Kế thừa 1 lớp',
                'dapAnD' => 'Kế thừa không toàn bộ',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 76,
                'noiDung' => 'Kế thừa bảo vệ nghĩa là?',
                'dapAnA' => 'Chỉ lớp con truy cập',
                'dapAnB' => 'Ai cũng truy cập',
                'dapAnC' => 'Không ai truy cập',
                'dapAnD' => 'Truy cập toàn cục',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 77,
                'noiDung' => 'Base class nghĩa là?',
                'dapAnA' => 'Lớp cơ sở',
                'dapAnB' => 'Lớp kế thừa',
                'dapAnC' => 'Lớp chính',
                'dapAnD' => 'Lớp tĩnh',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 78,
                'noiDung' => 'Derived class nghĩa là?',
                'dapAnA' => 'Lớp dẫn xuất',
                'dapAnB' => 'Lớp chính',
                'dapAnC' => 'Lớp cơ sở',
                'dapAnD' => 'Lớp tĩnh',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 79,
                'noiDung' => 'Access specifier nào cho kế thừa công khai?',
                'dapAnA' => 'public',
                'dapAnB' => 'private',
                'dapAnC' => 'protected',
                'dapAnD' => 'friend',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 80,
                'noiDung' => 'Access specifier nào kế thừa bảo vệ?',
                'dapAnA' => 'protected',
                'dapAnB' => 'public',
                'dapAnC' => 'private',
                'dapAnD' => 'virtual',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:53:57',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 8,
                'created_at' => '2025-07-06 17:53:57',
                'updated_at' => '2025-07-06 17:53:57',
            ],
            [
                'maCH' => 81,
                'noiDung' => 'Đa hình là?',
                'dapAnA' => '1 giao diện nhiều thực hiện',
                'dapAnB' => '1 giao diện 1 thực hiện',
                'dapAnC' => 'Không có giao diện',
                'dapAnD' => 'Chỉ 1 cách duy nhất',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 82,
                'noiDung' => 'Đa hình biên dịch là?',
                'dapAnA' => 'Overloading',
                'dapAnB' => 'Overriding',
                'dapAnC' => 'Interface',
                'dapAnD' => 'Abstract',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 83,
                'noiDung' => 'Đa hình chạy thời gian là?',
                'dapAnA' => 'Overriding',
                'dapAnB' => 'Overloading',
                'dapAnC' => 'Interface',
                'dapAnD' => 'Abstract',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 84,
                'noiDung' => 'Overloading là?',
                'dapAnA' => 'Nhiều hàm cùng tên khác tham số',
                'dapAnB' => '1 hàm nhiều tên',
                'dapAnC' => 'Không có hàm',
                'dapAnD' => '1 hàm 1 tham số',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 85,
                'noiDung' => 'Overriding là?',
                'dapAnA' => 'Lớp con định nghĩa lại hàm lớp cha',
                'dapAnB' => 'Hàm giống nhau',
                'dapAnC' => 'Không định nghĩa lại',
                'dapAnD' => 'Hàm riêng biệt',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 86,
                'noiDung' => 'Từ khóa virtual dùng để?',
                'dapAnA' => 'Đa hình động',
                'dapAnB' => 'Đa hình tĩnh',
                'dapAnC' => 'Không đa hình',
                'dapAnD' => 'Chống đa hình',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 87,
                'noiDung' => 'Pure virtual function là?',
                'dapAnA' => 'Hàm ảo thuần túy',
                'dapAnB' => 'Hàm thực',
                'dapAnC' => 'Hàm riêng',
                'dapAnD' => 'Hàm main',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 88,
                'noiDung' => 'Interface là?',
                'dapAnA' => 'Chỉ định các hàm cần định nghĩa',
                'dapAnB' => 'Định nghĩa sẵn',
                'dapAnC' => 'Không hàm',
                'dapAnD' => 'Chứa biến toàn cục',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 89,
                'noiDung' => 'Abstract class là?',
                'dapAnA' => 'Chứa hàm thuần ảo',
                'dapAnB' => 'Không có hàm',
                'dapAnC' => 'Không có biến',
                'dapAnD' => 'Hàm static',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 90,
                'noiDung' => 'Đa hình giúp?',
                'dapAnA' => 'Mã linh hoạt',
                'dapAnB' => 'Khó mở rộng',
                'dapAnC' => 'Tăng lỗi',
                'dapAnD' => 'Giảm tái sử dụng',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:20',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 9,
                'created_at' => '2025-07-06 17:54:20',
                'updated_at' => '2025-07-06 17:54:20',
            ],
            [
                'maCH' => 91,
                'noiDung' => 'Ngoại lệ là?',
                'dapAnA' => 'Lỗi xảy ra khi chạy',
                'dapAnB' => 'Lỗi biên dịch',
                'dapAnC' => 'Lỗi cú pháp',
                'dapAnD' => 'Lỗi giao diện',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 92,
                'noiDung' => 'Từ khóa bắt ngoại lệ?',
                'dapAnA' => 'try',
                'dapAnB' => 'catch',
                'dapAnC' => 'throw',
                'dapAnD' => 'throws',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 93,
                'noiDung' => 'Từ khóa xử lý ngoại lệ?',
                'dapAnA' => 'catch',
                'dapAnB' => 'try',
                'dapAnC' => 'throw',
                'dapAnD' => 'throws',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 94,
                'noiDung' => 'Từ khóa ném ngoại lệ?',
                'dapAnA' => 'throw',
                'dapAnB' => 'try',
                'dapAnC' => 'catch',
                'dapAnD' => 'throws',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 95,
                'noiDung' => 'I/O là?',
                'dapAnA' => 'Input/Output',
                'dapAnB' => 'Inside/Outside',
                'dapAnC' => 'Internal/Output',
                'dapAnD' => 'Internet/Output',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 96,
                'noiDung' => 'C++ I/O dùng?',
                'dapAnA' => 'cin, cout',
                'dapAnB' => 'printf, scanf',
                'dapAnC' => 'System.out.println',
                'dapAnD' => 'print',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 97,
                'noiDung' => 'Đọc file dùng?',
                'dapAnA' => 'ifstream',
                'dapAnB' => 'ofstream',
                'dapAnC' => 'fstream',
                'dapAnD' => 'fileinput',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 98,
                'noiDung' => 'Ghi file dùng?',
                'dapAnA' => 'ofstream',
                'dapAnB' => 'ifstream',
                'dapAnC' => 'fileinput',
                'dapAnD' => 'cin',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 99,
                'noiDung' => 'fstream dùng cho?',
                'dapAnA' => 'Đọc ghi file',
                'dapAnB' => 'Chỉ đọc file',
                'dapAnC' => 'Chỉ ghi file',
                'dapAnD' => 'Chỉ xóa file',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 100,
                'noiDung' => 'Xử lý ngoại lệ giúp?',
                'dapAnA' => 'Chương trình an toàn',
                'dapAnB' => 'Tăng lỗi',
                'dapAnC' => 'Giảm hiệu quả',
                'dapAnD' => 'Khó đọc',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 00:54:47',
                'maNguoiTao' => 3,
                'maMonHoc' => 2,
                'maChuong' => 10,
                'created_at' => '2025-07-06 17:54:47',
                'updated_at' => '2025-07-06 17:54:47',
            ],
            [
                'maCH' => 101,
                'noiDung' => 'Python bị ảnh hưởng bởi?',
                'dapAnA' => 'C và C++',
                'dapAnB' => 'Java và Perl',
                'dapAnC' => 'Lisp và Haskell',
                'dapAnD' => 'Tất cả đều đúng',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 102,
                'noiDung' => 'Phần mở rộng tên file Python là?',
                'dapAnA' => '.py',
                'dapAnB' => '.pyi',
                'dapAnC' => '.pyc và .pyd',
                'dapAnD' => 'Tất cả đều đúng',
                'dapAnDung' => 'D',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 103,
                'noiDung' => 'Python xuất hiện lần đầu tiên vào?',
                'dapAnA' => 'January 1982',
                'dapAnB' => 'February 1991',
                'dapAnC' => 'December 1987',
                'dapAnD' => 'July 2001',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 104,
                'noiDung' => 'Python được tạo ra bởi?',
                'dapAnA' => 'Guido van Rossum',
                'dapAnB' => 'James Gosling',
                'dapAnC' => 'Dennis Ritchie',
                'dapAnD' => 'Bjarne Stroustrup',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 105,
                'noiDung' => 'Python là?',
                'dapAnA' => 'ngôn ngữ lập trình đa năng, thông dịch, cấp cao',
                'dapAnB' => 'ngôn ngữ lập trình hướng đối tượng',
                'dapAnC' => 'ngôn ngữ lập trình thủ tục, hàm, cấu trúc',
                'dapAnD' => 'tất cả đều đúng',
                'dapAnDung' => 'D',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 106,
                'noiDung' => 'Câu lệnh nào sau đây đúng để in chuỗi “Hello World!”?',
                'dapAnA' => 'print(\"Hello, World!\")',
                'dapAnB' => 'printf(\"Hello, World!\")',
                'dapAnC' => 'console(\"Hello, World!\")',
                'dapAnD' => 'System.out.print(\"Hello, World!\")',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 107,
                'noiDung' => 'Python được phát triển như sự kế thừa của?',
                'dapAnA' => 'Java',
                'dapAnB' => 'Lisp',
                'dapAnC' => 'ABC',
                'dapAnD' => 'C++',
                'dapAnDung' => 'C',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 108,
                'noiDung' => 'Điều nào được coi là chú thích trong Python?',
                'dapAnA' => '# Đây là một chú thích',
                'dapAnB' => '\"\"\" Đây là một chú thích \"\"\"',
                'dapAnC' => '\'Đây là một chú thích\'',
                'dapAnD' => 'Tất cả đều đúng',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 109,
                'noiDung' => 'Trình biên dịch mặc định cho Python là?',
                'dapAnA' => 'Jython',
                'dapAnB' => 'Cython',
                'dapAnC' => 'PyPy',
                'dapAnD' => 'ActivePython',
                'dapAnDung' => 'C',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:03:04',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 11,
                'created_at' => '2025-07-06 18:03:04',
                'updated_at' => '2025-07-06 18:03:04',
            ],
            [
                'maCH' => 110,
                'noiDung' => 'Tên nào không thể là tên biến Python?',
                'dapAnA' => 'Int_1',
                'dapAnB' => 'true',
                'dapAnC' => 'var-2',
                'dapAnD' => 'name3',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 111,
                'noiDung' => 'Cái nào không phải là kiểu dữ liệu Python?',
                'dapAnA' => 'int',
                'dapAnB' => 'string',
                'dapAnC' => 'char',
                'dapAnD' => 'set',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 112,
                'noiDung' => 'Kết quả của num=4+0j; print(type(num))?',
                'dapAnA' => '<class \'int\'>',
                'dapAnB' => '<class \'float\'>',
                'dapAnC' => '<class \'real\'>',
                'dapAnD' => '<class \'complex\'>',
                'dapAnDung' => 'D',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 113,
                'noiDung' => 'Kết quả của print(5//2)?',
                'dapAnA' => '1',
                'dapAnB' => '2',
                'dapAnC' => '2.5',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 114,
                'noiDung' => 'Kết quả của a=\'Python\'+\".py\"; print(a)?',
                'dapAnA' => 'Python.py',
                'dapAnB' => '\'Python\'+\".py\"',
                'dapAnC' => 'Python+.py',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 115,
                'noiDung' => 'Kết quả của set1={1,5,6,4,3}; print(set1)?',
                'dapAnA' => '{1,5,6,4,3}',
                'dapAnB' => '{1, 3, 4, 5, 6}',
                'dapAnC' => '1,5,6,4,3',
                'dapAnD' => '1, 3, 4, 5, 6',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 116,
                'noiDung' => 'Toán tử tính lũy thừa?',
                'dapAnA' => 'x^y',
                'dapAnB' => 'x*y',
                'dapAnC' => 'x**y',
                'dapAnD' => 'x***y',
                'dapAnDung' => 'C',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 117,
                'noiDung' => 'Độ dài tối đa của mã identifier trong python?',
                'dapAnA' => '256',
                'dapAnB' => '64',
                'dapAnC' => '128',
                'dapAnD' => 'Tất cả đều sai',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 118,
                'noiDung' => 'Kết quả của var=\"a \"*2*3; print(var)?',
                'dapAnA' => 'a * 2 * 3',
                'dapAnB' => 'a * 6',
                'dapAnC' => 'a a a a a a',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 119,
                'noiDung' => 'Phát biểu sai về tên biến?',
                'dapAnA' => 'Tên biến có thể dài tùy ý',
                'dapAnB' => 'Tên biến có thể chứa cả chữ cái và số',
                'dapAnC' => 'Tên biến có thể bắt đầu bằng dấu gạch dưới',
                'dapAnD' => 'Tên biến có thể bắt đầu bằng số',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:36',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 12,
                'created_at' => '2025-07-06 18:03:36',
                'updated_at' => '2025-07-06 18:03:36',
            ],
            [
                'maCH' => 120,
                'noiDung' => 'Kết quả c=0; for i in \"abc xyz\": c+=1; print(c)?',
                'dapAnA' => '0',
                'dapAnB' => '6',
                'dapAnC' => '7',
                'dapAnD' => '8',
                'dapAnDung' => 'C',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 121,
                'noiDung' => 'Đoạn code while(i<10)... chạy bao lần?',
                'dapAnA' => '3',
                'dapAnB' => '4',
                'dapAnC' => '5',
                'dapAnD' => '10',
                'dapAnDung' => 'C',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 122,
                'noiDung' => 'Kết quả sign(0)?',
                'dapAnA' => 'Positive!',
                'dapAnB' => 'Negative!',
                'dapAnC' => 'Zero!',
                'dapAnD' => '0',
                'dapAnDung' => 'C',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 123,
                'noiDung' => 'Kết quả number(2)?',
                'dapAnA' => '2',
                'dapAnB' => 'two',
                'dapAnC' => 'three',
                'dapAnD' => 'No Output!',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 124,
                'noiDung' => 'Không phải câu lệnh điều khiển?',
                'dapAnA' => 'break',
                'dapAnB' => 'continue',
                'dapAnC' => 'end',
                'dapAnD' => 'Tất cả đều sai',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 125,
                'noiDung' => 'Chức năng của continue?',
                'dapAnA' => 'Code dưới bỏ qua cho lần lặp đó',
                'dapAnB' => 'Code dưới thực thi',
                'dapAnC' => 'Dừng vòng lặp',
                'dapAnD' => 'Tất cả sai',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 126,
                'noiDung' => 'Từ khóa break?',
                'dapAnA' => 'Đưa quyền kiểm soát ra khỏi vòng lặp',
                'dapAnB' => 'Không dùng được',
                'dapAnC' => 'Phải đi với else',
                'dapAnD' => 'Chỉ dùng trong if',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 127,
                'noiDung' => 'Kết quả for num in range(10,14)...?',
                'dapAnA' => '11 13',
                'dapAnB' => '10 11 12 13',
                'dapAnC' => '10 12 14',
                'dapAnD' => '10 12',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 128,
                'noiDung' => 'Kết quả for num in range(-2,-5,-1)...?',
                'dapAnA' => '-2, -3, -4,',
                'dapAnB' => '-2, -1, 0,',
                'dapAnC' => '-2, -1, -3, -4,',
                'dapAnD' => '-2, -1, 0, 1, 2, 3,',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 129,
                'noiDung' => 'Kết quả var=10...?',
                'dapAnA' => '10',
                'dapAnB' => '20',
                'dapAnC' => '21',
                'dapAnD' => '30',
                'dapAnDung' => 'C',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:03:51',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 13,
                'created_at' => '2025-07-06 18:03:51',
                'updated_at' => '2025-07-06 18:03:51',
            ],
            [
                'maCH' => 130,
                'noiDung' => 'Phát biểu đúng về hàm do người dùng định nghĩa?',
                'dapAnA' => 'Hàm nên có return cuối',
                'dapAnB' => 'Tên hàm xác định bởi người dùng',
                'dapAnC' => 'Thân hàm thụt vào, bao {}',
                'dapAnD' => 'Thân hàm không thụt vào, bao {}',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 131,
                'noiDung' => 'Lệnh truy cập docstring?',
                'dapAnA' => 'functionName.doc()',
                'dapAnB' => 'docstring(functionName)',
                'dapAnC' => 'functionName.__doc__',
                'dapAnD' => 'functioName.__doc__()',
                'dapAnDung' => 'C',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 132,
                'noiDung' => 'Cú pháp định nghĩa hàm đối số độ dài thay đổi?',
                'dapAnA' => 'def fun(**vals):...',
                'dapAnB' => 'def fun(vals[]):...',
                'dapAnC' => 'def fun(*vals):...',
                'dapAnD' => 'Tất cả đều đúng',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 133,
                'noiDung' => 'Kết quả def func(): print(\"Hi!\")?',
                'dapAnA' => 'Hi!',
                'dapAnB' => '\'Hi!\'',
                'dapAnC' => 'Không xuất gì',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 134,
                'noiDung' => 'Kết quả fun(1,2) với def fun(x,y=0,z)?',
                'dapAnA' => '-1',
                'dapAnB' => '3',
                'dapAnC' => 'Giá trị rác',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 135,
                'noiDung' => 'Kết quả print(name)? với name=\"Python\"...',
                'dapAnA' => 'Python',
                'dapAnB' => 'Hello world!',
                'dapAnC' => 'PythonHello world!',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 136,
                'noiDung' => 'Kết quả n=4...f1()?',
                'dapAnA' => '4',
                'dapAnB' => '16',
                'dapAnC' => '256',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'D',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 137,
                'noiDung' => 'Hàm range() trả về?',
                'dapAnA' => 'list',
                'dapAnB' => 'range',
                'dapAnC' => 'set',
                'dapAnD' => 'dictionary',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 138,
                'noiDung' => 'Giá trị mặc định bước nhảy range()?',
                'dapAnA' => '0',
                'dapAnB' => '1',
                'dapAnC' => '-1',
                'dapAnD' => 'Bắt buộc truyền',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 139,
                'noiDung' => 'Kết quả cal(3) với def cal(num1=1,num2=2)?',
                'dapAnA' => '2',
                'dapAnB' => '6',
                'dapAnC' => 'Giá trị rác',
                'dapAnD' => 'Báo lỗi',
                'dapAnDung' => 'B',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:04:20',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 14,
                'created_at' => '2025-07-06 18:04:20',
                'updated_at' => '2025-07-06 18:04:20',
            ],
            [
                'maCH' => 140,
                'noiDung' => 'Kết quả print(type({}))?',
                'dapAnA' => '<class \'set\'>',
                'dapAnB' => '<class \'list\'>',
                'dapAnC' => '<class \'tuple\'>',
                'dapAnD' => '<class \'dict\'>',
                'dapAnDung' => 'D',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 141,
                'noiDung' => 'Kết quả str1=\"Information\"; print(str1[2:8])?',
                'dapAnA' => 'format',
                'dapAnB' => 'norma',
                'dapAnC' => 'formatio',
                'dapAnD' => 'nformati',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 142,
                'noiDung' => 'Cái nào không phải thuộc tính list?',
                'dapAnA' => 'Có thứ tự',
                'dapAnB' => 'Có thể thay đổi',
                'dapAnC' => 'Chỉ chứa phần tử cùng loại',
                'dapAnD' => 'Có thể chứa giá trị trùng lặp',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 143,
                'noiDung' => 'Cái nào không thể thêm phần tử vào list?',
                'dapAnA' => 'add()',
                'dapAnB' => 'insert()',
                'dapAnC' => 'append()',
                'dapAnD' => 'extend()',
                'dapAnDung' => 'A',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 144,
                'noiDung' => 'Điều nào không phải tính chất tuple?',
                'dapAnA' => 'có thứ tự',
                'dapAnB' => 'tính bất biến',
                'dapAnC' => 'không cho phép giá trị trùng',
                'dapAnD' => 'Tất cả đúng',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 145,
                'noiDung' => 'Cái nào dùng làm khóa dictionary?',
                'dapAnA' => 'List',
                'dapAnB' => 'Tuple',
                'dapAnC' => 'Set',
                'dapAnD' => 'Dictionary',
                'dapAnDung' => 'B',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 146,
                'noiDung' => 'Hàm không áp dụng cho tuple?',
                'dapAnA' => 'len()',
                'dapAnB' => 'sorted()',
                'dapAnC' => 'index()',
                'dapAnD' => 'sort()',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 147,
                'noiDung' => 'Kết quả dict={1:\'r\',2:6,1:5,3:\'y\'}; print(dict)?',
                'dapAnA' => '{1: 5, 2: 6, 3: \'y\'}',
                'dapAnB' => '{1:\'r\',2:6,1:5,3:\'y\'}',
                'dapAnC' => '{1:\'r\',2:6,3:\'y\'}',
                'dapAnD' => '{2:6,1:\'r\',3:\'y\'}',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 148,
                'noiDung' => 'Kết quả dict={0:\'r\',4:\'y\',7.6:5}; dict[2]=5; print(dict)?',
                'dapAnA' => '{0: \'r\', 2: 5, 4: \'y\', 7.6: 5}',
                'dapAnB' => '{0: \'r\', 4: \'y\', 2: 5}',
                'dapAnC' => '{2: 5, 0: \'r\', 4: \'y\', 7.6: 5}',
                'dapAnD' => '{0: \'r\', 4: \'y\', 7.6: 5, 2: 5}',
                'dapAnDung' => 'A',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 149,
                'noiDung' => '____, ____, ____ lần lượt cho list, dict, tuple?',
                'dapAnA' => '[ ], { }, ( )',
                'dapAnB' => '{ }, ( ), [ ]',
                'dapAnC' => '( ), [ ], { }',
                'dapAnD' => '( ), { }, [ ]',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:06:02',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 15,
                'created_at' => '2025-07-06 18:06:02',
                'updated_at' => '2025-07-06 18:06:02',
            ],
            [
                'maCH' => 150,
                'noiDung' => 'Cú pháp tạo dự án Django?',
                'dapAnA' => 'py manage.py start-django my_project',
                'dapAnB' => 'django-admin startproject my_project',
                'dapAnC' => 'django startproject my_project',
                'dapAnD' => 'py start-django my_project',
                'dapAnDung' => 'B',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:06:15',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 16,
                'created_at' => '2025-07-06 18:06:15',
                'updated_at' => '2025-07-06 18:06:15',
            ],
            [
                'maCH' => 151,
                'noiDung' => 'File không phải của dự án Django?',
                'dapAnA' => 'settings.py',
                'dapAnB' => 'manage.py',
                'dapAnC' => 'templates.py',
                'dapAnD' => '__init__.py',
                'dapAnDung' => 'C',
                'doKho' => 'Dễ',
                'ngayTao' => '2025-07-07 01:06:15',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 16,
                'created_at' => '2025-07-06 18:06:15',
                'updated_at' => '2025-07-06 18:06:15',
            ],
            [
                'maCH' => 152,
                'noiDung' => 'Mã RGB (255,0,0) OpenCV hiểu là?',
                'dapAnA' => 'Blue',
                'dapAnB' => 'Green',
                'dapAnC' => 'Yellow',
                'dapAnD' => 'Cyan',
                'dapAnDung' => 'A',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:06:15',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 16,
                'created_at' => '2025-07-06 18:06:15',
                'updated_at' => '2025-07-06 18:06:15',
            ],
            [
                'maCH' => 153,
                'noiDung' => 'Câu lệnh import cv2?',
                'dapAnA' => 'Import SciPy',
                'dapAnB' => 'Import NumPy',
                'dapAnC' => 'Import OpenCV Python',
                'dapAnD' => 'Import hiển thị ảnh',
                'dapAnDung' => 'C',
                'doKho' => 'Khó',
                'ngayTao' => '2025-07-07 01:06:15',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 16,
                'created_at' => '2025-07-06 18:06:15',
                'updated_at' => '2025-07-06 18:06:15',
            ],
            [
                'maCH' => 154,
                'noiDung' => 'OpenCV lưu pixel RGB thứ tự?',
                'dapAnA' => 'GBR',
                'dapAnB' => 'RGB',
                'dapAnC' => 'BRG',
                'dapAnD' => 'BGR',
                'dapAnDung' => 'D',
                'doKho' => 'Trung Bình',
                'ngayTao' => '2025-07-07 01:06:15',
                'maNguoiTao' => 4,
                'maMonHoc' => 3,
                'maChuong' => 16,
                'created_at' => '2025-07-06 18:06:15',
                'updated_at' => '2025-07-06 18:06:15',
            ],
        ]);
    }
}
