<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaiKhoanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tai_khoan')->insert([
            [
                'maTK' => 1,
                'email' => 'hung.nguyen@caothang.edu.vn',
                'matKhau' => '$2y$12$WFf/Olo.RvwvMoXVGKRfhero783j299JLQdoLXKmovBfDL9WCzwsu',
                'hoTen' => 'Nguyễn Văn Hùng',
                'anhDaiDien' => null,
                'vaiTro' => 'quanTri',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 18:31:42',
            ],
            [
                'maTK' => 2,
                'email' => 'nga.le@caothang.edu.vn',
                'matKhau' => '$2y$12$qoL10apo4RC18mWcjmeCZunJLomAawuE9Vc24teyNBLLA7dLC1sz2',
                'hoTen' => 'Lê Thị Nga',
                'anhDaiDien' => null,
                'vaiTro' => 'giangVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-07-04 02:08:57',
            ],
            [
                'maTK' => 3,
                'email' => 'kien.phan@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Phan Tấn Kiên',
                'anhDaiDien' => null,
                'vaiTro' => 'giangVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 13:05:58',
            ],
            [
                'maTK' => 4,
                'email' => 'dung.nguyen@caothang.edu.vn',
                'matKhau' => '$2y$12$1Iqd4v9xeJxWRh2/D7g/NOF1fZjlhnACBF7oZmwJ3a.wiVH3oPYaS',
                'hoTen' => 'Nguyễn Hữu Dũng',
                'anhDaiDien' => null,
                'vaiTro' => 'giangVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-07-06 12:51:58',
            ],
            [
                'maTK' => 5,
                'email' => 'mai.pham@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Phạm Thị Mai',
                'anhDaiDien' => null,
                'vaiTro' => 'sinhVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-07-06 19:11:07',
            ],
            [
                'maTK' => 6,
                'email' => 'tuan.tran@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Trần Anh Tuấn',
                'anhDaiDien' => null,
                'vaiTro' => 'sinhVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 13:05:58',
            ],
            [
                'maTK' => 7,
                'email' => 'huong.le@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Lê Ngọc Hương',
                'anhDaiDien' => null,
                'vaiTro' => 'sinhVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 13:05:58',
            ],
            [
                'maTK' => 8,
                'email' => 'bao.vo@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Võ Hoàng Bảo',
                'anhDaiDien' => null,
                'vaiTro' => 'sinhVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 13:05:58',
            ],
            [
                'maTK' => 9,
                'email' => 'hien.nguyen@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Nguyễn Thị Hiền',
                'anhDaiDien' => null,
                'vaiTro' => 'sinhVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 13:05:58',
            ],
            [
                'maTK' => 10,
                'email' => 'tam.dang@caothang.edu.vn',
                'matKhau' => '$2y$12$x27XQY0JT.dg3dvzWd2C2e/Jze3mCZGmGA1CUE5lvknzHg1IpJKx2',
                'hoTen' => 'Đặng Gia Tâm',
                'anhDaiDien' => null,
                'vaiTro' => 'sinhVien',
                'doiMK' => 0,
                'ngayTao' => '2025-06-23 20:05:58',
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-23 13:05:58',
                'updated_at' => '2025-06-23 13:05:58',
            ],
            [
                'maTK' => 11,
                'email' => 'nhkhanh@caothang.edu.vn',
                'matKhau' => '$2y$12$hj6e/NenU/7tdhWVWR6xcOd20XYrVPQ54x4Emq.2E6r.N93QrNqBK',
                'hoTen' => 'Nguyễn Hoàng Khánh',
                'anhDaiDien' => null,
                'vaiTro' => 'giangVien',
                'doiMK' => 0,
                'ngayTao' => null,
                'last_seen_de_thi_at' => null,
                'created_at' => '2025-06-25 02:39:06',
                'updated_at' => '2025-06-25 02:39:06',
            ],
        ]);
    }
}
